// Datos de ejemplo para el MODO PREVIEW (sin Supabase).
// Solo se usan en las rutas /preview para mostrar cómo funciona la app.
import type {
  Category,
  Order,
  OrderItem,
  Plan,
  Product,
  SubscriptionPayment,
  Tenant,
  TenantSettings,
} from "@/lib/supabase/types";
import type { MenuPayload } from "@/app/m/[tenant]/[table]/menu-client";

const now = new Date();
const iso = (daysAgo = 0) =>
  new Date(now.getTime() - daysAgo * 86400000).toISOString();

export const mockPlans: Plan[] = [
  {
    id: "plan-basico",
    code: "basico",
    name: "Básico",
    price_usd: 29,
    is_active: true,
    sort_order: 1,
    features: {
      max_languages: 1,
      max_products: 30,
      max_categories: 5,
      max_tables: 8,
      advanced_reports: false,
      full_branding: false,
    },
  },
  {
    id: "plan-estandar",
    code: "estandar",
    name: "Estándar",
    price_usd: 49,
    is_active: true,
    sort_order: 2,
    features: {
      max_languages: 2,
      max_products: 100,
      max_categories: 20,
      max_tables: 30,
      advanced_reports: true,
      full_branding: true,
    },
  },
  {
    id: "plan-empresarial",
    code: "empresarial",
    name: "Empresarial",
    price_usd: 99,
    is_active: true,
    sort_order: 3,
    features: {
      max_languages: 3,
      max_products: null,
      max_categories: null,
      max_tables: null,
      advanced_reports: true,
      full_branding: true,
    },
  },
];

export const mockTenants: Tenant[] = [
  {
    id: "t-demo",
    name: "Soda Demo Datfud",
    slug: "demo",
    status: "active",
    plan_id: "plan-estandar",
    trial_ends_at: null,
    owner_email: "demo@datfud.com",
    owner_name: "Demo Owner",
    phone: "+506 8888 8888",
    created_at: iso(40),
    updated_at: iso(1),
  },
  {
    id: "t-2",
    name: "Restaurante La Cosecha",
    slug: "la-cosecha",
    status: "active",
    plan_id: "plan-empresarial",
    trial_ends_at: null,
    owner_email: "info@lacosecha.cr",
    owner_name: "María Jiménez",
    phone: "+506 2222 1111",
    created_at: iso(25),
    updated_at: iso(2),
  },
  {
    id: "t-3",
    name: "Café del Parque",
    slug: "cafe-parque",
    status: "trial",
    plan_id: "plan-basico",
    trial_ends_at: iso(-20),
    owner_email: "hola@cafeparque.com",
    owner_name: "Luis Mora",
    phone: null,
    created_at: iso(8),
    updated_at: iso(1),
  },
  {
    id: "t-4",
    name: "Pizzería Napoli",
    slug: "napoli",
    status: "suspended",
    plan_id: "plan-estandar",
    trial_ends_at: null,
    owner_email: "napoli@gmail.com",
    owner_name: "Marco Rossi",
    phone: null,
    created_at: iso(60),
    updated_at: iso(5),
  },
];

export const mockPayments: SubscriptionPayment[] = [
  {
    id: "pay-1",
    tenant_id: "t-demo",
    plan_id: "plan-estandar",
    amount_usd: 49,
    period_start: iso(30).slice(0, 10),
    period_end: iso(0).slice(0, 10),
    paid_at: iso(30),
    status: "paid",
    approved_by: null,
    notes: null,
    created_at: iso(30),
  },
  {
    id: "pay-2",
    tenant_id: "t-2",
    plan_id: "plan-empresarial",
    amount_usd: 99,
    period_start: iso(25).slice(0, 10),
    period_end: iso(-5).slice(0, 10),
    paid_at: iso(25),
    status: "paid",
    approved_by: null,
    notes: null,
    created_at: iso(25),
  },
  {
    id: "pay-3",
    tenant_id: "t-4",
    plan_id: "plan-estandar",
    amount_usd: 49,
    period_start: iso(40).slice(0, 10),
    period_end: iso(10).slice(0, 10),
    paid_at: null,
    status: "overdue",
    approved_by: null,
    notes: "Pago vencido",
    created_at: iso(40),
  },
];

export const mockSettings: TenantSettings = {
  tenant_id: "t-demo",
  currency_code: "CRC",
  default_language: "es",
  enabled_languages: ["es", "en"],
  theme: { primary: "#22503a", accent: "#b8923f" },
  logo_url: null,
  restaurant_name: "Soda Demo Datfud",
  address: "Avenida Central, San José",
  phone: "+506 8888 8888",
  created_at: iso(40),
  updated_at: iso(1),
};

export const mockCategories: Category[] = [
  {
    id: "c-comidas",
    tenant_id: "t-demo",
    name_i18n: { es: "Comidas", en: "Meals", pt: "Refeições" },
    description_i18n: {},
    image_url: null,
    sort_order: 1,
    is_active: true,
    created_at: iso(40),
    updated_at: iso(40),
  },
  {
    id: "c-bebidas",
    tenant_id: "t-demo",
    name_i18n: { es: "Bebidas", en: "Drinks", pt: "Bebidas" },
    description_i18n: {},
    image_url: null,
    sort_order: 2,
    is_active: true,
    created_at: iso(40),
    updated_at: iso(40),
  },
];

export const mockProducts: Product[] = [
  {
    id: "p-casado",
    tenant_id: "t-demo",
    category_id: "c-comidas",
    name_i18n: { es: "Casado", en: "Casado", pt: "Casado" },
    description_i18n: {
      es: "Arroz, frijoles, carne y ensalada",
      en: "Rice, beans, meat and salad",
      pt: "Arroz, feijão, carne e salada",
    },
    price: 3500,
    image_url:
      "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=300&q=70",
    is_available: true,
    is_active: true,
    sort_order: 1,
    created_at: iso(40),
    updated_at: iso(40),
  },
  {
    id: "p-gallo",
    tenant_id: "t-demo",
    category_id: "c-comidas",
    name_i18n: { es: "Gallo Pinto", en: "Gallo Pinto", pt: "Gallo Pinto" },
    description_i18n: { es: "Arroz con frijoles típico" },
    price: 2500,
    image_url:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=300&q=70",
    is_available: true,
    is_active: true,
    sort_order: 2,
    created_at: iso(40),
    updated_at: iso(40),
  },
  {
    id: "p-fresco",
    tenant_id: "t-demo",
    category_id: "c-bebidas",
    name_i18n: { es: "Fresco Natural", en: "Natural Drink", pt: "Suco Natural" },
    description_i18n: { es: "Fresco del día" },
    price: 1200,
    image_url:
      "https://i.pinimg.com/736x/03/5a/a5/035aa532a09b8be3bb8dad25aa808f6e.jpg",
    is_available: true,
    is_active: true,
    sort_order: 1,
    created_at: iso(40),
    updated_at: iso(40),
  },
  {
    id: "p-cafe",
    tenant_id: "t-demo",
    category_id: "c-bebidas",
    name_i18n: { es: "Café Chorreado", en: "Brewed Coffee", pt: "Café" },
    description_i18n: { es: "Café costarricense recién hecho" },
    price: 900,
    image_url: null,
    is_available: false,
    is_active: true,
    sort_order: 2,
    created_at: iso(40),
    updated_at: iso(40),
  },
];

export const mockOrders: Order[] = [
  {
    id: "o-1",
    tenant_id: "t-demo",
    table_id: "tab-1",
    status: "pending",
    currency_code: "CRC",
    subtotal: 4700,
    total: 4700,
    customer_note: "Sin cebolla por favor",
    created_at: iso(0),
    updated_at: iso(0),
  },
  {
    id: "o-2",
    tenant_id: "t-demo",
    table_id: "tab-2",
    status: "preparing",
    currency_code: "CRC",
    subtotal: 2500,
    total: 2500,
    customer_note: null,
    created_at: iso(0),
    updated_at: iso(0),
  },
  {
    id: "o-3",
    tenant_id: "t-demo",
    table_id: "tab-1",
    status: "paid",
    currency_code: "CRC",
    subtotal: 6900,
    total: 6900,
    customer_note: null,
    created_at: iso(1),
    updated_at: iso(1),
  },
  {
    id: "o-4",
    tenant_id: "t-demo",
    table_id: "tab-3",
    status: "delivered",
    currency_code: "CRC",
    subtotal: 3500,
    total: 3500,
    customer_note: null,
    created_at: iso(1),
    updated_at: iso(1),
  },
];

export const mockOrderItems: Record<string, OrderItem[]> = {
  "o-1": [
    {
      id: "oi-1",
      order_id: "o-1",
      tenant_id: "t-demo",
      product_id: "p-casado",
      product_name_snapshot: "Casado",
      unit_price_snapshot: 3500,
      quantity: 1,
      line_total: 3500,
      note: null,
    },
    {
      id: "oi-2",
      order_id: "o-1",
      tenant_id: "t-demo",
      product_id: "p-fresco",
      product_name_snapshot: "Fresco Natural",
      unit_price_snapshot: 1200,
      quantity: 1,
      line_total: 1200,
      note: null,
    },
  ],
  "o-2": [
    {
      id: "oi-3",
      order_id: "o-2",
      tenant_id: "t-demo",
      product_id: "p-gallo",
      product_name_snapshot: "Gallo Pinto",
      unit_price_snapshot: 2500,
      quantity: 1,
      line_total: 2500,
      note: null,
    },
  ],
  "o-3": [
    {
      id: "oi-4",
      order_id: "o-3",
      tenant_id: "t-demo",
      product_id: "p-casado",
      product_name_snapshot: "Casado",
      unit_price_snapshot: 3500,
      quantity: 2,
      line_total: 7000,
      note: null,
    },
  ],
  "o-4": [
    {
      id: "oi-5",
      order_id: "o-4",
      tenant_id: "t-demo",
      product_id: "p-casado",
      product_name_snapshot: "Casado",
      unit_price_snapshot: 3500,
      quantity: 1,
      line_total: 3500,
      note: null,
    },
  ],
};

export const mockDailySales = [
  { day: iso(0).slice(0, 10), orders_count: 2, revenue: 10400, currency_code: "CRC" },
  { day: iso(1).slice(0, 10), orders_count: 5, revenue: 18700, currency_code: "CRC" },
  { day: iso(2).slice(0, 10), orders_count: 4, revenue: 14200, currency_code: "CRC" },
  { day: iso(3).slice(0, 10), orders_count: 6, revenue: 21500, currency_code: "CRC" },
];

export const mockTopProducts = [
  { name: "Casado", units: 18, revenue: 63000 },
  { name: "Gallo Pinto", units: 11, revenue: 27500 },
  { name: "Fresco Natural", units: 9, revenue: 10800 },
  { name: "Café Chorreado", units: 6, revenue: 5400 },
];

export const mockMenuPayload: MenuPayload = {
  tenant: { id: "t-demo", name: "Soda Demo Datfud", slug: "demo" },
  table: { id: "tab-1", label: "Mesa 1" },
  settings: {
    currency_code: "CRC",
    default_language: "es",
    enabled_languages: ["es", "en", "pt"],
    theme: { primary: "#22503a", accent: "#b8923f" },
    logo_url: null,
    restaurant_name: "Soda Demo Datfud",
  },
  categories: mockCategories.map((c) => ({
    id: c.id,
    name_i18n: c.name_i18n,
    sort_order: c.sort_order,
  })),
  products: mockProducts
    .filter((p) => p.is_available)
    .map((p) => ({
      id: p.id,
      category_id: p.category_id,
      name_i18n: p.name_i18n,
      description_i18n: p.description_i18n,
      price: p.price,
      image_url: p.image_url,
      sort_order: p.sort_order,
    })),
};
